project_id: '639352'
api_token: e269caef37e130da0e373898f502fb5a72b900da8557f18b3b2ea0a664f3535216d7c0837134cddd
preserve_hierarchy: 1
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
bundles:
  - 2
